// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// L1proj
NumericVector L1proj(NumericVector v, double z, double lambda0);
RcppExport SEXP _wavegrpreg_L1proj(SEXP vSEXP, SEXP zSEXP, SEXP lambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    rcpp_result_gen = Rcpp::wrap(L1proj(v, z, lambda0));
    return rcpp_result_gen;
END_RCPP
}
// L12proj
NumericVector L12proj(NumericVector eta, int M, int p, double z, double lambda0);
RcppExport SEXP _wavegrpreg_L12proj(SEXP etaSEXP, SEXP MSEXP, SEXP pSEXP, SEXP zSEXP, SEXP lambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    rcpp_result_gen = Rcpp::wrap(L12proj(eta, M, p, z, lambda0));
    return rcpp_result_gen;
END_RCPP
}
// SPG
Rcpp::List SPG(arma::mat W, arma::vec y, arma::mat Sigma, arma::vec sizes, double z, double lambda, double gamma, double a_min, double a_max, double sig1, double sig2, int Msave, int max1, int max2, double tol);
RcppExport SEXP _wavegrpreg_SPG(SEXP WSEXP, SEXP ySEXP, SEXP SigmaSEXP, SEXP sizesSEXP, SEXP zSEXP, SEXP lambdaSEXP, SEXP gammaSEXP, SEXP a_minSEXP, SEXP a_maxSEXP, SEXP sig1SEXP, SEXP sig2SEXP, SEXP MsaveSEXP, SEXP max1SEXP, SEXP max2SEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sizes(sizesSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type a_min(a_minSEXP);
    Rcpp::traits::input_parameter< double >::type a_max(a_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sig1(sig1SEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< int >::type Msave(MsaveSEXP);
    Rcpp::traits::input_parameter< int >::type max1(max1SEXP);
    Rcpp::traits::input_parameter< int >::type max2(max2SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(SPG(W, y, Sigma, sizes, z, lambda, gamma, a_min, a_max, sig1, sig2, Msave, max1, max2, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wavegrpreg_L1proj", (DL_FUNC) &_wavegrpreg_L1proj, 3},
    {"_wavegrpreg_L12proj", (DL_FUNC) &_wavegrpreg_L12proj, 5},
    {"_wavegrpreg_SPG", (DL_FUNC) &_wavegrpreg_SPG, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_wavegrpreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
