# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

L1proj <- function(v, z, lambda0) {
    .Call(`_wavegrpreg_L1proj`, v, z, lambda0)
}

L12proj <- function(eta, M, p, z, lambda0) {
    .Call(`_wavegrpreg_L12proj`, eta, M, p, z, lambda0)
}

SPG <- function(W, y, Sigma, sizes, z, lambda, gamma, a_min, a_max, sig1, sig2, Msave, max1, max2, tol) {
    .Call(`_wavegrpreg_SPG`, W, y, Sigma, sizes, z, lambda, gamma, a_min, a_max, sig1, sig2, Msave, max1, max2, tol)
}

